http:
    servers:
        - listen: 8789
          location:
            - chaos_injection:
                abort:
                    code: 0
                    probability: 0
                error:
                    code: 507
                    probability: 59
                    response: ""
                latency:
                    probability: 0
                    time: 0
              headers:
                Content-Type: application/json
              method: GET
              path: /api/v1/ruta/del/recurso
              response: '{"message": "success"}'
              schema: ""
              status_code: 200
          logger: true
          logger_path: ./log/servidorPrueba
          name: servidorPrueba
          version: 2.0.0
